kvm_hosts:
  hosts:
    localhost
  vars:
    base_image_name: "ubuntu-20.04-minimal-cloudimg-amd64.img"
    base_image_url:  "https://cloud-images.ubuntu.com/minimal/releases/focal/release/{{ base_image_name }}"
    # TODO think of a way to get sha256 sum from https://cloud-images.ubuntu.com/minimal/releases/focal/release/SHA256SUMS
    base_image_sha256sum: "2c1c414d1015966c97aacd647b4491747099aef4a161bcc588e70bdffc6d9e0c"
    base_image_download_dest: "/tmp/{{ base_image_name }}"

    libvirt_pool_name: "vm-img-pool"
    libvirt_pool_dir: "/var/lib/libvirt/images"
    vm_volume_name: vm1-volume
    vm_volume_capacity_GB: '8'  # Gigabytes

    vm_image_size_GB: '8'  # Gigabytes
    vm_name: gitlab-study-vm
    vm_name_fqdn: gitlab-study-vm
    vm_vcpus: '1'
    vm_ram_mb: '1024'
    vm_net: vnet01

    ssh_authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCX2bD/1l1d7kqjg0/u3FsgXReqwlPC2o+7LhVPZGFuZzst66dgh/PjmHGxaZeLlqwH2wEWSAxElkTELtWNmQi9/FrRVatp4B/dN5dhvI9nsayeMda9MZ4ZtuHGe6Te9ZoDd5/V4ujxtB8R75D/j5cbBYdaXW+WHRCumE80Jymmo0fGeWSIoAvxodeP5Xu9NoliHdo41BigLIOXU6JCavujFRvo+ag2Wxy2rR4oc7e+HGDXFZtXrRffRmTa5rLQD2KtRMKmFJyswr39x3kA/fKOKZ3oMlgpmJI5xNb1Ignn6FVAYNvi4rUCaEe6sWEIa+DKR0Mu+l1CG9xguU3wRJ5+aB2j5dZxRuI6QLQY67FRjeUVjXXPBCN+FjuHhoPVjRatqhQiAzrKb4KUOEzDOXDLgem785tzpPM7pKRy/Yzy2ZSXmOpEBjqhNam26VBZTXZYv6zxcK8Ypr2OekgUnbDjkms7cyGyuLcrMDPM8qCZkkCBYi8dSQQ+JYyuCydTVvU="
    admin_user_name: admin
    admin_user_password_hash: "$6$r2yiCi.YAtKRCBFK$S8//V8.dSLFRFRE5ft3nnzZlIOiAAz5UlQJOaMJQHr3EVi7ptaROQCfWlgCm63rV59s2CYm7DOYmILpYaAyl31" # plaintext password is "rootpw" (without quotes)

apache2_hosts:
  hosts:
    192.168.123.2
