gitlab_hosts:
  hosts:
    192.168.123.2
  vars:
    # Ansible Galaxy role 'geerlingguy.swap'
    swap_file_size_mb: '2048'
    swap_swappiness: '10'
    swap_file_state: present
    # GitLab configuration
    external_url: 'http://192.168.123.2'
    gitlab_email_enabled: 'false'
    letsencrypt_enable: 'false'
    letsencrypt_auto_renew: 'false'
    # optimizations for memory-constrained environment
    sidekiq_max_concurrency: '10'
    GITALY_COMMAND_SPAWN_MAX_PARALLEL: '2'
    gitaly_ruby_max_rss: '200_000_000'
    gitaly_concurrency_smart_http_service_post_receive_pack_max_per_repo: '3'
    gitaly_concurrency_ssh_service_ssh_upload_pack_max_per_repo: '3'
    gitaly_cgroups_count: '2'
    gitaly_cgroups_memory_limit: '500000'
    # TODO configure memory handling
