- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install the necessary dependencies ignoring "install_recommends"
  ansible.builtin.package:
    name:
      - curl
      - openssh-server
      - ca-certificates
      - tzdata
      - perl
    state: latest
    install_recommends: no

- name: Set Postfix option type
  ansible.builtin.debconf:
    name=postfix
    question="postfix/main_mailer_type"
    value="'Local only'"
    vtype="string"

- name: Set Postfix option hostname
  ansible.builtin.debconf:
    name=postifx
    question="postfix/mailname"
    value="gitlab-study"
    vtype="string"

- name: Install postfix
  ansible.builtin.package:
    name: postfix
    state: latest
    install_recommends: no

- name: Download GitLab CE installation script
  ansible.builtin.get_url:
    url: 'https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh'
    dest: /tmp/script.deb.sh
    mode: '0770'

- name: Set up GitLab CE's repository using script
  ansible.builtin.command: bash /tmp/script.deb.sh

- name: Update apt cache and install GitLab CE package
  ansible.builtin.apt:
    name: gitlab-ce
    state: latest
    update_cache: yes

- name: Template out GitLab configuration file
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: '0600'
  notify: GitLab reconfigure
